version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: contact_form_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contact_form_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contact_form_network

volumes:
  postgres_data:

networks:
  contact_form_network:
    driver: bridge
